LOCAL_API_BASE = "https://my.api.link/v1"
REMOTE_API_BASE = "https://api.openai.com/v1"

OPENAI_KEY = "sk-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
TX_SECRET_ID = "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
TX_SECRET_KEY = "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
